// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, title, description, difficulty, xp_reward, gold_reward)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at
`

type CreateHabitParams struct {
	UserID      int64       `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Difficulty  string      `json:"difficulty"`
	XpReward    int32       `json:"xp_reward"`
	GoldReward  int32       `json:"gold_reward"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.XpReward,
		arg.GoldReward,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.XpReward,
		&i.GoldReward,
		&i.IsActive,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCompletedDate,
		&i.CreatedAt,
	)
	return i, err
}

const createHabitStatReward = `-- name: CreateHabitStatReward :one
INSERT INTO habit_stat_rewards (habit_id, stat_code, amount)
VALUES ($1, $2, $3)
ON CONFLICT (habit_id, stat_code) DO UPDATE SET amount = EXCLUDED.amount
RETURNING habit_id, stat_code, amount
`

type CreateHabitStatRewardParams struct {
	HabitID  int64  `json:"habit_id"`
	StatCode string `json:"stat_code"`
	Amount   int32  `json:"amount"`
}

func (q *Queries) CreateHabitStatReward(ctx context.Context, arg CreateHabitStatRewardParams) (HabitStatReward, error) {
	row := q.db.QueryRow(ctx, createHabitStatReward, arg.HabitID, arg.StatCode, arg.Amount)
	var i HabitStatReward
	err := row.Scan(&i.HabitID, &i.StatCode, &i.Amount)
	return i, err
}

const deactivateHabit = `-- name: DeactivateHabit :one
UPDATE habits
SET is_active = false
WHERE id = $1
RETURNING id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at
`

func (q *Queries) DeactivateHabit(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRow(ctx, deactivateHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.XpReward,
		&i.GoldReward,
		&i.IsActive,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCompletedDate,
		&i.CreatedAt,
	)
	return i, err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at FROM habits
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHabitByID(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.XpReward,
		&i.GoldReward,
		&i.IsActive,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCompletedDate,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveHabits = `-- name: ListActiveHabits :many
SELECT id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at FROM habits
WHERE user_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveHabits(ctx context.Context, userID int64) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listActiveHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.XpReward,
			&i.GoldReward,
			&i.IsActive,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LastCompletedDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitStatRewards = `-- name: ListHabitStatRewards :many
SELECT habit_id, stat_code, amount FROM habit_stat_rewards
WHERE habit_id = $1
`

func (q *Queries) ListHabitStatRewards(ctx context.Context, habitID int64) ([]HabitStatReward, error) {
	rows, err := q.db.Query(ctx, listHabitStatRewards, habitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitStatReward{}
	for rows.Next() {
		var i HabitStatReward
		if err := rows.Scan(&i.HabitID, &i.StatCode, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET title = $2, description = $3, difficulty = $4, xp_reward = $5, gold_reward = $6
WHERE id = $1
RETURNING id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at
`

type UpdateHabitParams struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Difficulty  string      `json:"difficulty"`
	XpReward    int32       `json:"xp_reward"`
	GoldReward  int32       `json:"gold_reward"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.XpReward,
		arg.GoldReward,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.XpReward,
		&i.GoldReward,
		&i.IsActive,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCompletedDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateHabitStreak = `-- name: UpdateHabitStreak :one
UPDATE habits
SET
    current_streak      = $2,
    longest_streak      = $3,
    last_completed_date = $4
WHERE id = $1
RETURNING id, user_id, title, description, difficulty, xp_reward, gold_reward, is_active, current_streak, longest_streak, last_completed_date, created_at
`

type UpdateHabitStreakParams struct {
	ID                int64       `json:"id"`
	CurrentStreak     int32       `json:"current_streak"`
	LongestStreak     int32       `json:"longest_streak"`
	LastCompletedDate pgtype.Date `json:"last_completed_date"`
}

func (q *Queries) UpdateHabitStreak(ctx context.Context, arg UpdateHabitStreakParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabitStreak,
		arg.ID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastCompletedDate,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.XpReward,
		&i.GoldReward,
		&i.IsActive,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCompletedDate,
		&i.CreatedAt,
	)
	return i, err
}
