// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type QuestStatus string

const (
	QuestStatusPending   QuestStatus = "pending"
	QuestStatusCompleted QuestStatus = "completed"
	QuestStatusFailed    QuestStatus = "failed"
	QuestStatusExpired   QuestStatus = "expired"
)

func (e *QuestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestStatus(s)
	case string:
		*e = QuestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestStatus: %T", src)
	}
	return nil
}

type NullQuestStatus struct {
	QuestStatus QuestStatus `json:"quest_status"`
	Valid       bool        `json:"valid"` // Valid is true if QuestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestStatus), nil
}

type QuestType string

const (
	QuestTypeDaily QuestType = "daily"
	QuestTypeMain  QuestType = "main"
	QuestTypeBoss  QuestType = "boss"
)

func (e *QuestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestType(s)
	case string:
		*e = QuestType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestType: %T", src)
	}
	return nil
}

type NullQuestType struct {
	QuestType QuestType `json:"quest_type"`
	Valid     bool      `json:"valid"` // Valid is true if QuestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestType), nil
}

type Habit struct {
	ID                int64       `json:"id"`
	UserID            int64       `json:"user_id"`
	Title             string      `json:"title"`
	Description       pgtype.Text `json:"description"`
	Difficulty        string      `json:"difficulty"`
	XpReward          int32       `json:"xp_reward"`
	GoldReward        int32       `json:"gold_reward"`
	IsActive          bool        `json:"is_active"`
	CurrentStreak     int32       `json:"current_streak"`
	LongestStreak     int32       `json:"longest_streak"`
	LastCompletedDate pgtype.Date `json:"last_completed_date"`
	CreatedAt         time.Time   `json:"created_at"`
}

type HabitStatReward struct {
	HabitID  int64  `json:"habit_id"`
	StatCode string `json:"stat_code"`
	Amount   int32  `json:"amount"`
}

type Quest struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	HabitID     pgtype.Int8        `json:"habit_id"`
	Type        QuestType          `json:"type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	XpReward    int32              `json:"xp_reward"`
	GoldReward  int32              `json:"gold_reward"`
	Status      QuestStatus        `json:"status"`
	DueDate     pgtype.Date        `json:"due_date"`
	DeadlineAt  pgtype.Timestamptz `json:"deadline_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type QuestStatReward struct {
	QuestID  int64  `json:"quest_id"`
	StatCode string `json:"stat_code"`
	Amount   int32  `json:"amount"`
}

type Stat struct {
	Code string      `json:"code"`
	Name string      `json:"name"`
	Icon pgtype.Text `json:"icon"`
}

type User struct {
	ID         int64       `json:"id"`
	TelegramID int64       `json:"telegram_id"`
	Username   pgtype.Text `json:"username"`
	Timezone   string      `json:"timezone"`
	Rank       string      `json:"rank"`
	Level      int32       `json:"level"`
	Xp         int64       `json:"xp"`
	Gold       int64       `json:"gold"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type UserStat struct {
	UserID   int64  `json:"user_id"`
	StatCode string `json:"stat_code"`
	Value    int32  `json:"value"`
}

type XpGoldTransaction struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	QuestID   pgtype.Int8 `json:"quest_id"`
	XpDelta   int32       `json:"xp_delta"`
	GoldDelta int32       `json:"gold_delta"`
	Reason    string      `json:"reason"`
	CreatedAt time.Time   `json:"created_at"`
}
