// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CompleteQuest(ctx context.Context, id int64) (Quest, error)
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateHabitStatReward(ctx context.Context, arg CreateHabitStatRewardParams) (HabitStatReward, error)
	CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error)
	CreateQuestStatReward(ctx context.Context, arg CreateQuestStatRewardParams) (QuestStatReward, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateXPGoldTransaction(ctx context.Context, arg CreateXPGoldTransactionParams) (XpGoldTransaction, error)
	DeactivateHabit(ctx context.Context, id int64) (Habit, error)
	ExpirePendingDailyQuests(ctx context.Context, arg ExpirePendingDailyQuestsParams) ([]Quest, error)
	GetDailyQuestForHabit(ctx context.Context, arg GetDailyQuestForHabitParams) (Quest, error)
	GetHabitByID(ctx context.Context, id int64) (Habit, error)
	GetQuestByID(ctx context.Context, id int64) (Quest, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	GetUserStat(ctx context.Context, arg GetUserStatParams) (UserStat, error)
	InitUserStats(ctx context.Context, userID int64) error
	ListActiveHabits(ctx context.Context, userID int64) ([]Habit, error)
	ListDailyQuestsByDate(ctx context.Context, arg ListDailyQuestsByDateParams) ([]Quest, error)
	ListHabitStatRewards(ctx context.Context, habitID int64) ([]HabitStatReward, error)
	ListPendingQuestsByUser(ctx context.Context, userID int64) ([]Quest, error)
	ListQuestStatRewards(ctx context.Context, questID int64) ([]QuestStatReward, error)
	ListStats(ctx context.Context) ([]Stat, error)
	ListUserStats(ctx context.Context, userID int64) ([]UserStat, error)
	ListUserTransactions(ctx context.Context, arg ListUserTransactionsParams) ([]XpGoldTransaction, error)
	UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error)
	UpdateHabitStreak(ctx context.Context, arg UpdateHabitStreakParams) (Habit, error)
	UpdateUserRank(ctx context.Context, arg UpdateUserRankParams) (User, error)
	UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (User, error)
	UpdateUserXPGold(ctx context.Context, arg UpdateUserXPGoldParams) (User, error)
	UpsertUserStat(ctx context.Context, arg UpsertUserStatParams) (UserStat, error)
}

var _ Querier = (*Queries)(nil)
