// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeQuest = `-- name: CompleteQuest :one
UPDATE quests
SET status = 'completed', completed_at = now()
WHERE id = $1
RETURNING id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at
`

func (q *Queries) CompleteQuest(ctx context.Context, id int64) (Quest, error) {
	row := q.db.QueryRow(ctx, completeQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.XpReward,
		&i.GoldReward,
		&i.Status,
		&i.DueDate,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (user_id, habit_id, type, title, description, xp_reward, gold_reward, due_date, deadline_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at
`

type CreateQuestParams struct {
	UserID      int64              `json:"user_id"`
	HabitID     pgtype.Int8        `json:"habit_id"`
	Type        QuestType          `json:"type"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	XpReward    int32              `json:"xp_reward"`
	GoldReward  int32              `json:"gold_reward"`
	DueDate     pgtype.Date        `json:"due_date"`
	DeadlineAt  pgtype.Timestamptz `json:"deadline_at"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.UserID,
		arg.HabitID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.XpReward,
		arg.GoldReward,
		arg.DueDate,
		arg.DeadlineAt,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.XpReward,
		&i.GoldReward,
		&i.Status,
		&i.DueDate,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestStatReward = `-- name: CreateQuestStatReward :one
INSERT INTO quest_stat_rewards (quest_id, stat_code, amount)
VALUES ($1, $2, $3)
RETURNING quest_id, stat_code, amount
`

type CreateQuestStatRewardParams struct {
	QuestID  int64  `json:"quest_id"`
	StatCode string `json:"stat_code"`
	Amount   int32  `json:"amount"`
}

func (q *Queries) CreateQuestStatReward(ctx context.Context, arg CreateQuestStatRewardParams) (QuestStatReward, error) {
	row := q.db.QueryRow(ctx, createQuestStatReward, arg.QuestID, arg.StatCode, arg.Amount)
	var i QuestStatReward
	err := row.Scan(&i.QuestID, &i.StatCode, &i.Amount)
	return i, err
}

const expirePendingDailyQuests = `-- name: ExpirePendingDailyQuests :many
UPDATE quests
SET status = 'expired'
WHERE user_id = $1 AND type = 'daily' AND due_date < $2 AND status = 'pending'
RETURNING id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at
`

type ExpirePendingDailyQuestsParams struct {
	UserID  int64       `json:"user_id"`
	DueDate pgtype.Date `json:"due_date"`
}

func (q *Queries) ExpirePendingDailyQuests(ctx context.Context, arg ExpirePendingDailyQuestsParams) ([]Quest, error) {
	rows, err := q.db.Query(ctx, expirePendingDailyQuests, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.XpReward,
			&i.GoldReward,
			&i.Status,
			&i.DueDate,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyQuestForHabit = `-- name: GetDailyQuestForHabit :one
SELECT id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at FROM quests
WHERE habit_id = $1 AND due_date = $2 AND type = 'daily'
LIMIT 1
`

type GetDailyQuestForHabitParams struct {
	HabitID pgtype.Int8 `json:"habit_id"`
	DueDate pgtype.Date `json:"due_date"`
}

func (q *Queries) GetDailyQuestForHabit(ctx context.Context, arg GetDailyQuestForHabitParams) (Quest, error) {
	row := q.db.QueryRow(ctx, getDailyQuestForHabit, arg.HabitID, arg.DueDate)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.XpReward,
		&i.GoldReward,
		&i.Status,
		&i.DueDate,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestByID = `-- name: GetQuestByID :one
SELECT id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at FROM quests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetQuestByID(ctx context.Context, id int64) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuestByID, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.XpReward,
		&i.GoldReward,
		&i.Status,
		&i.DueDate,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDailyQuestsByDate = `-- name: ListDailyQuestsByDate :many
SELECT id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at FROM quests
WHERE user_id = $1 AND type = 'daily' AND due_date = $2
ORDER BY created_at
`

type ListDailyQuestsByDateParams struct {
	UserID  int64       `json:"user_id"`
	DueDate pgtype.Date `json:"due_date"`
}

func (q *Queries) ListDailyQuestsByDate(ctx context.Context, arg ListDailyQuestsByDateParams) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listDailyQuestsByDate, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.XpReward,
			&i.GoldReward,
			&i.Status,
			&i.DueDate,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingQuestsByUser = `-- name: ListPendingQuestsByUser :many
SELECT id, user_id, habit_id, type, title, description, xp_reward, gold_reward, status, due_date, deadline_at, completed_at, created_at FROM quests
WHERE user_id = $1 AND status = 'pending'
ORDER BY created_at
`

func (q *Queries) ListPendingQuestsByUser(ctx context.Context, userID int64) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listPendingQuestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quest{}
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.XpReward,
			&i.GoldReward,
			&i.Status,
			&i.DueDate,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestStatRewards = `-- name: ListQuestStatRewards :many
SELECT quest_id, stat_code, amount FROM quest_stat_rewards
WHERE quest_id = $1
`

func (q *Queries) ListQuestStatRewards(ctx context.Context, questID int64) ([]QuestStatReward, error) {
	rows, err := q.db.Query(ctx, listQuestStatRewards, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestStatReward{}
	for rows.Next() {
		var i QuestStatReward
		if err := rows.Scan(&i.QuestID, &i.StatCode, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
