// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createXPGoldTransaction = `-- name: CreateXPGoldTransaction :one
INSERT INTO xp_gold_transactions (user_id, quest_id, xp_delta, gold_delta, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, quest_id, xp_delta, gold_delta, reason, created_at
`

type CreateXPGoldTransactionParams struct {
	UserID    int64       `json:"user_id"`
	QuestID   pgtype.Int8 `json:"quest_id"`
	XpDelta   int32       `json:"xp_delta"`
	GoldDelta int32       `json:"gold_delta"`
	Reason    string      `json:"reason"`
}

func (q *Queries) CreateXPGoldTransaction(ctx context.Context, arg CreateXPGoldTransactionParams) (XpGoldTransaction, error) {
	row := q.db.QueryRow(ctx, createXPGoldTransaction,
		arg.UserID,
		arg.QuestID,
		arg.XpDelta,
		arg.GoldDelta,
		arg.Reason,
	)
	var i XpGoldTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestID,
		&i.XpDelta,
		&i.GoldDelta,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserStat = `-- name: GetUserStat :one
SELECT user_id, stat_code, value FROM user_stats
WHERE user_id = $1 AND stat_code = $2
`

type GetUserStatParams struct {
	UserID   int64  `json:"user_id"`
	StatCode string `json:"stat_code"`
}

func (q *Queries) GetUserStat(ctx context.Context, arg GetUserStatParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStat, arg.UserID, arg.StatCode)
	var i UserStat
	err := row.Scan(&i.UserID, &i.StatCode, &i.Value)
	return i, err
}

const initUserStats = `-- name: InitUserStats :exec
INSERT INTO user_stats (user_id, stat_code, value)
SELECT $1, code, 0 FROM stats
ON CONFLICT (user_id, stat_code) DO NOTHING
`

func (q *Queries) InitUserStats(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, initUserStats, userID)
	return err
}

const listStats = `-- name: ListStats :many
SELECT code, name, icon FROM stats
ORDER BY code
`

func (q *Queries) ListStats(ctx context.Context) ([]Stat, error) {
	rows, err := q.db.Query(ctx, listStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stat{}
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.Code, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStats = `-- name: ListUserStats :many
SELECT user_id, stat_code, value FROM user_stats
WHERE user_id = $1
ORDER BY stat_code
`

func (q *Queries) ListUserStats(ctx context.Context, userID int64) ([]UserStat, error) {
	rows, err := q.db.Query(ctx, listUserStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserStat{}
	for rows.Next() {
		var i UserStat
		if err := rows.Scan(&i.UserID, &i.StatCode, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTransactions = `-- name: ListUserTransactions :many
SELECT id, user_id, quest_id, xp_delta, gold_delta, reason, created_at FROM xp_gold_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUserTransactionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListUserTransactions(ctx context.Context, arg ListUserTransactionsParams) ([]XpGoldTransaction, error) {
	rows, err := q.db.Query(ctx, listUserTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []XpGoldTransaction{}
	for rows.Next() {
		var i XpGoldTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestID,
			&i.XpDelta,
			&i.GoldDelta,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserStat = `-- name: UpsertUserStat :one
INSERT INTO user_stats (user_id, stat_code, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, stat_code) DO UPDATE
    SET value = user_stats.value + EXCLUDED.value
RETURNING user_id, stat_code, value
`

type UpsertUserStatParams struct {
	UserID   int64  `json:"user_id"`
	StatCode string `json:"stat_code"`
	Value    int32  `json:"value"`
}

func (q *Queries) UpsertUserStat(ctx context.Context, arg UpsertUserStatParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, upsertUserStat, arg.UserID, arg.StatCode, arg.Value)
	var i UserStat
	err := row.Scan(&i.UserID, &i.StatCode, &i.Value)
	return i, err
}
